// ============================================================
// oodle — Database Types
// Auto-generated by: supabase gen types typescript --project-id vfaordrzgogfmtxwlpgg
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      messages: {
        Row: {
          content: string
          created_at: string
          id: string
          sender_id: string
          thread_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          sender_id: string
          thread_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          sender_id?: string
          thread_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      post_purchases: {
        Row: {
          amount: number
          buyer_id: string
          created_at: string
          creator_id: string
          id: string
          post_id: string
          stripe_payment_intent_id: string | null
          thread_id: string
        }
        Insert: {
          amount: number
          buyer_id: string
          created_at?: string
          creator_id: string
          id?: string
          post_id: string
          stripe_payment_intent_id?: string | null
          thread_id: string
        }
        Update: {
          amount?: number
          buyer_id?: string
          created_at?: string
          creator_id?: string
          id?: string
          post_id?: string
          stripe_payment_intent_id?: string | null
          thread_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "post_purchases_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "post_purchases_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "post_purchases_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "post_purchases_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          answer_count: number
          caption: string | null
          created_at: string
          creator_id: string
          id: string
          image_urls: string[]
          location_address: string | null
          location_lat: number | null
          location_lng: number | null
          price: number | null
          question_count: number
          updated_at: string
        }
        Insert: {
          answer_count?: number
          caption?: string | null
          created_at?: string
          creator_id: string
          id?: string
          image_urls?: string[]
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          price?: number | null
          question_count?: number
          updated_at?: string
        }
        Update: {
          answer_count?: number
          caption?: string | null
          created_at?: string
          creator_id?: string
          id?: string
          image_urls?: string[]
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          price?: number | null
          question_count?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      answer_ratings: {
        Row: {
          created_at: string
          id: string
          rater_id: string
          rating: number
          thread_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          rater_id: string
          rating: number
          thread_id: string
        }
        Update: {
          created_at?: string
          id?: string
          rater_id?: string
          rating?: number
          thread_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "answer_ratings_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "answer_ratings_rater_id_fkey"
            columns: ["rater_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      threads: {
        Row: {
          answer_blocks: Json | null
          answer_text: string | null
          answered_at: string | null
          asker_has_viewed: boolean
          created_at: string
          creator_id: string
          fan_id: string
          id: string
          post_id: string
          price: number
          purchase_count: number
          status: string
          updated_at: string
        }
        Insert: {
          answer_blocks?: Json | null
          answer_text?: string | null
          answered_at?: string | null
          asker_has_viewed?: boolean
          created_at?: string
          creator_id: string
          fan_id: string
          id?: string
          post_id: string
          price?: number
          purchase_count?: number
          status?: string
          updated_at?: string
        }
        Update: {
          answer_blocks?: Json | null
          answer_text?: string | null
          answered_at?: string | null
          asker_has_viewed?: boolean
          created_at?: string
          creator_id?: string
          fan_id?: string
          id?: string
          post_id?: string
          price?: number
          purchase_count?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "threads_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "threads_fan_id_fkey"
            columns: ["fan_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "threads_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_questions: {
        Row: {
          id: string
          creator_id: string
          asker_id: string
          question: string
          status: string
          upvote_count: number
          answer_post_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          creator_id: string
          asker_id: string
          question: string
          status?: string
          upvote_count?: number
          answer_post_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          creator_id?: string
          asker_id?: string
          question?: string
          status?: string
          upvote_count?: number
          answer_post_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_questions_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_questions_asker_id_fkey"
            columns: ["asker_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_questions_answer_post_id_fkey"
            columns: ["answer_post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_question_upvotes: {
        Row: {
          question_id: string
          user_id: string
        }
        Insert: {
          question_id: string
          user_id: string
        }
        Update: {
          question_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_question_upvotes_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "profile_questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_question_upvotes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_following: {
        Row: {
          created_at: string
          creator_id: string
          follower_id: string
        }
        Insert: {
          created_at?: string
          creator_id: string
          follower_id: string
        }
        Update: {
          created_at?: string
          creator_id?: string
          follower_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_following_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_following_follower_id_fkey"
            columns: ["follower_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      blocked_users: {
        Row: {
          blocker_id: string
          blocked_id: string
          created_at: string
        }
        Insert: {
          blocker_id: string
          blocked_id: string
          created_at?: string
        }
        Update: {
          blocker_id?: string
          blocked_id?: string
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: "blocked_users_blocker_id_fkey"; columns: ["blocker_id"]; referencedRelation: "users"; referencedColumns: ["id"] },
          { foreignKeyName: "blocked_users_blocked_id_fkey"; columns: ["blocked_id"]; referencedRelation: "users"; referencedColumns: ["id"] },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          bio: string | null
          categories: string[] | null
          created_at: string
          default_answer_price: number | null
          display_name: string | null
          email: string
          email_notifications: boolean
          followers_count: number
          following_count: number
          id: string
          onboarding_completed: boolean
          public_profile: boolean
          push_notifications: boolean
          response_rate: number | null
          role: string
          show_answer_price: boolean
          stripe_account_id: string | null
          stripe_onboarded: boolean | null
          token_balance: number
          updated_at: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          categories?: string[] | null
          created_at?: string
          default_answer_price?: number | null
          display_name?: string | null
          email: string
          email_notifications?: boolean
          followers_count?: number
          following_count?: number
          id: string
          onboarding_completed?: boolean
          public_profile?: boolean
          push_notifications?: boolean
          response_rate?: number | null
          role: string
          show_answer_price?: boolean
          stripe_account_id?: string | null
          stripe_onboarded?: boolean | null
          token_balance?: number
          updated_at?: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          categories?: string[] | null
          created_at?: string
          default_answer_price?: number | null
          display_name?: string | null
          email?: string
          email_notifications?: boolean
          followers_count?: number
          following_count?: number
          id?: string
          onboarding_completed?: boolean
          public_profile?: boolean
          push_notifications?: boolean
          response_rate?: number | null
          role?: string
          show_answer_price?: boolean
          stripe_account_id?: string | null
          stripe_onboarded?: boolean | null
          token_balance?: number
          updated_at?: string
          username?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_feed_data: { Args: { p_user_id: string }; Returns: Json }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      upvote_profile_question: {
        Args: { p_question_id: string; p_user_id: string }
        Returns: void
      }
      unvote_profile_question: {
        Args: { p_question_id: string; p_user_id: string }
        Returns: void
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U }
      ? U
      : never
    : never

// ── Convenience row types ──────────────────────────────────────────────────────
export type UserRow                  = Tables<'users'>
export type PostRow                  = Tables<'posts'>
export type ThreadRow                = Tables<'threads'>
export type MessageRow               = Tables<'messages'>
export type PostPurchaseRow          = Tables<'post_purchases'>
export type UserFollowingRow         = Tables<'user_following'>
export type AnswerRatingRow          = Tables<'answer_ratings'>
export type ProfileQuestionRow       = Tables<'profile_questions'>
export type ProfileQuestionUpvoteRow = Tables<'profile_question_upvotes'>

// ── Custom domain types ────────────────────────────────────────────────────────
export type Role         = 'fan' | 'creator'
export type ThreadStatus = 'clarification' | 'answered'

/** Answer block union — matches the JSONB stored in threads.answer_blocks */
export interface TextBlock     { id: string; type: 'text';     content: string }
export interface PhotoBlock    { id: string; type: 'photo';    url: string }
export interface LocationBlock { id: string; type: 'location'; address: string; coords?: [number, number] }
export interface AudioBlock    { id: string; type: 'audio';    url: string; duration: number }
export interface ListBlock     { id: string; type: 'list';     items: string[]; ordered: boolean }
export type AnswerBlock = TextBlock | PhotoBlock | LocationBlock | AudioBlock | ListBlock

/** Thread with joined participant profiles and messages */
export interface ThreadWithParticipants extends ThreadRow {
  post:     Pick<PostRow, 'id' | 'image_urls' | 'caption'>
  creator:  Pick<UserRow, 'id' | 'username' | 'display_name' | 'avatar_url' | 'response_rate'>
  fan:      Pick<UserRow, 'id' | 'username' | 'display_name' | 'avatar_url'>
  messages: MessageWithSender[]
}

export interface MessageWithSender extends MessageRow {
  sender: Pick<UserRow, 'id' | 'username' | 'avatar_url'>
}

/** Public-safe profile (no stripe_account_id or email) */
export type PublicProfile = Omit<UserRow, 'email' | 'stripe_account_id'>
