// ============================================================
// OODLE — Mock feed data for explore mode / empty DB
// ============================================================

import type { ComposedPost } from './feedComposer'
import type { ThreadWithParticipants } from './database.types'
import type { ProfileQuestion } from '../services/profileQuestionService'
import type { FeedItem } from '../services/feedService'

const now = new Date()
function ago(minutes: number): string {
  return new Date(now.getTime() - minutes * 60 * 1000).toISOString()
}

export const MOCK_FEED: ComposedPost[] = [
  {
    id: 'mock-1',
    creator_id: 'mock-creator-1',
    creator_username: 'alexwatts',
    creator_display_name: 'Alex Watts',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=11',
    creator_response_rate: 94,
    categories: ['finance', 'investing'],
    created_at: ago(18),
    caption: 'The single most important thing I did in my 20s was automate my investments before I could spend the money. Not budgeting. Not tracking expenses. Automation. Here\'s the exact setup I use that grew my portfolio to $240K by 28.',
    image_urls: [],
    price: 15,
    location_address: null,
    question_count: 34,
    answer_count: 12,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-2',
    creator_id: 'mock-creator-2',
    creator_username: 'siennafit',
    creator_display_name: 'Sienna Marlow',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=5',
    creator_response_rate: 88,
    categories: ['fitness', 'nutrition'],
    created_at: ago(45),
    caption: 'I trained 6 days a week for 3 years and barely changed. Then I read one study that flipped everything I thought I knew about progressive overload. Sharing the full breakdown + my revised program.',
    image_urls: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
    ],
    price: null,
    location_address: null,
    question_count: 58,
    answer_count: 22,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-3',
    creator_id: 'mock-creator-3',
    creator_username: 'marclens',
    creator_display_name: 'Marc Delacroix',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=15',
    creator_response_rate: 97,
    categories: ['photography', 'creative'],
    created_at: ago(90),
    caption: 'Shot this entire campaign on a $300 lens. Art directors never believe me. The secret isn\'t the gear — it\'s the one lighting trick I use in every single shoot that makes cheap glass look expensive.',
    image_urls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    ],
    price: 8,
    location_address: 'Paris, France',
    question_count: 91,
    answer_count: 41,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-4',
    creator_id: 'mock-creator-4',
    creator_username: 'drjordanmind',
    creator_display_name: 'Dr. Jordan Ellis',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=33',
    creator_response_rate: 82,
    categories: ['mental-health', 'productivity'],
    created_at: ago(200),
    caption: 'Most productivity advice makes anxiety worse. I\'m a psychologist and I see this destroy high performers constantly. The framework I give my clients instead — and why it actually works with your nervous system, not against it.',
    image_urls: [],
    price: 20,
    location_address: null,
    question_count: 120,
    answer_count: 55,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-5',
    creator_id: 'mock-creator-5',
    creator_username: 'naomibuilds',
    creator_display_name: 'Naomi Park',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=47',
    creator_response_rate: 91,
    categories: ['startups', 'product'],
    created_at: ago(320),
    caption: 'We hit $10K MRR in 4 months with zero paid ads. The channel everyone ignores right now is doing most of the work. Happy to share the full breakdown — messaging strategy, conversion rates, everything.',
    image_urls: [
      'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    ],
    price: null,
    location_address: 'San Francisco, CA',
    question_count: 77,
    answer_count: 30,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-6',
    creator_id: 'mock-creator-6',
    creator_username: 'chefkaito',
    creator_display_name: 'Kaito Mori',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=53',
    creator_response_rate: 99,
    categories: ['food', 'cooking'],
    created_at: ago(480),
    caption: 'After 12 years as a Michelin-starred sous chef, the technique home cooks almost always miss isn\'t seasoning or heat — it\'s this one thing that separates restaurant food from everything else. Showing exactly how to do it.',
    image_urls: [
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    price: 12,
    location_address: 'Tokyo, Japan',
    question_count: 203,
    answer_count: 89,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-7',
    creator_id: 'mock-creator-2',
    creator_username: 'siennafit',
    creator_display_name: 'Sienna Marlow',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=5',
    creator_response_rate: 88,
    categories: ['fitness', 'nutrition'],
    created_at: ago(720),
    caption: 'The exact meal prep I do every Sunday that keeps me at 15% body fat year-round without tracking calories. 45 mins of prep, covers 80% of my meals. Full recipe list and macros included.',
    image_urls: [
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
    ],
    price: null,
    location_address: null,
    question_count: 44,
    answer_count: 18,
    is_purchased: false,
    _slot: 'followed',
  },
  {
    id: 'mock-8',
    creator_id: 'mock-creator-7',
    creator_username: 'taylordesigns',
    creator_display_name: 'Taylor Rhodes',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=25',
    creator_response_rate: 76,
    categories: ['design', 'ui'],
    created_at: ago(900),
    caption: 'I redesigned a fintech app\'s onboarding and conversion went from 31% to 67% in 3 weeks. The change was embarrassingly simple. Sharing the before/after and the principle behind it.',
    image_urls: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    ],
    price: 18,
    location_address: 'New York, NY',
    question_count: 65,
    answer_count: 28,
    is_purchased: false,
    _slot: 'discovery',
  },
  {
    id: 'mock-9',
    creator_id: 'mock-creator-1',
    creator_username: 'alexwatts',
    creator_display_name: 'Alex Watts',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=11',
    creator_response_rate: 94,
    categories: ['finance', 'tax'],
    created_at: ago(1200),
    caption: 'The tax move most W-2 employees don\'t know about that saved me $8,400 last year. Totally legal, takes 20 minutes to set up, and almost no one in your company is doing it.',
    image_urls: [],
    price: null,
    location_address: null,
    question_count: 189,
    answer_count: 71,
    is_purchased: false,
    _slot: 'followed',
  },
  {
    id: 'mock-10',
    creator_id: 'mock-creator-8',
    creator_username: 'riacodes',
    creator_display_name: 'Ria Sharma',
    creator_avatar_url: 'https://i.pravatar.cc/150?img=41',
    creator_response_rate: 85,
    categories: ['tech', 'career'],
    created_at: ago(1500),
    caption: 'Got offers from Google, Stripe, and Figma in the same month. The thing that actually moved the needle in interviews wasn\'t LeetCode — it was how I answered this one type of question differently than everyone else.',
    image_urls: [],
    price: 25,
    location_address: null,
    question_count: 312,
    answer_count: 140,
    is_purchased: false,
    _slot: 'discovery',
  },
]

// ─── Mock threads (inbox) ─────────────────────────────────────────────────────

const ME = {
  id: 'explore-guest',
  username: 'you',
  display_name: 'You (exploring)',
  avatar_url: null,
  response_rate: 94,
}

export const MOCK_THREADS: ThreadWithParticipants[] = [
  // ── Thread 1: answered — jessicaw asked about finance ──
  {
    id: 'mock-thread-1',
    post_id: 'mock-1',
    creator_id: 'explore-guest',
    fan_id: 'mock-fan-jessica',
    status: 'answered',
    price: 15,
    answer_blocks: null,
    answer_text: 'The key is automating transfers on payday — before the money hits your checking account. I use a standing order for 20% of every paycheck straight into a total market index fund. The trick is you never see the money so you never miss it.',
    answered_at: ago(120),
    asker_has_viewed: true,
    purchase_count: 47,
    created_at: ago(180),
    updated_at: ago(120),
    post: {
      id: 'mock-1',
      image_urls: [],
      caption: 'The single most important thing I did in my 20s was automate my investments…',
    },
    creator: { ...ME },
    fan: {
      id: 'mock-fan-jessica',
      username: 'jessicaw',
      display_name: 'Jessica W',
      avatar_url: 'https://i.pravatar.cc/150?img=9',
    },
    messages: [
      {
        id: 'mock-msg-1a',
        thread_id: 'mock-thread-1',
        sender_id: 'mock-fan-jessica',
        content: 'How did you actually start automating? Did you use a specific app or set it up through your employer?',
        created_at: ago(180),
        sender: { id: 'mock-fan-jessica', username: 'jessicaw', avatar_url: 'https://i.pravatar.cc/150?img=9' },
      },
      {
        id: 'mock-msg-1b',
        thread_id: 'mock-thread-1',
        sender_id: 'explore-guest',
        content: 'The key is automating transfers on payday — before the money hits your checking account. I use a standing order for 20% of every paycheck straight into a total market index fund. The trick is you never see the money so you never miss it.',
        created_at: ago(120),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
    ],
  },

  // ── Thread 2: answered — marcot asked about fitness ──
  {
    id: 'mock-thread-2',
    post_id: 'mock-2',
    creator_id: 'explore-guest',
    fan_id: 'mock-fan-marco',
    status: 'answered',
    price: 12,
    answer_blocks: null,
    answer_text: 'The Schoenfeld study showed training to failure isn\'t necessary — and is counterproductive. Switched from 4x10 same weight to 3x8 adding +2.5lbs every session. More progress in 6 months than the previous 2 years.',
    answered_at: ago(300),
    asker_has_viewed: true,
    purchase_count: 22,
    created_at: ago(400),
    updated_at: ago(300),
    post: {
      id: 'mock-2',
      image_urls: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80'],
      caption: 'I trained 6 days a week for 3 years and barely changed…',
    },
    creator: { ...ME },
    fan: {
      id: 'mock-fan-marco',
      username: 'marcot',
      display_name: 'Marco T',
      avatar_url: 'https://i.pravatar.cc/150?img=18',
    },
    messages: [
      {
        id: 'mock-msg-2a',
        thread_id: 'mock-thread-2',
        sender_id: 'mock-fan-marco',
        content: 'Which study changed your approach? And what specifically did you change about your programming?',
        created_at: ago(400),
        sender: { id: 'mock-fan-marco', username: 'marcot', avatar_url: 'https://i.pravatar.cc/150?img=18' },
      },
      {
        id: 'mock-msg-2b',
        thread_id: 'mock-thread-2',
        sender_id: 'explore-guest',
        content: 'The Schoenfeld study showed training to failure isn\'t necessary — and is counterproductive. Switched from 4x10 same weight to 3x8 adding +2.5lbs every session. More progress in 6 months than the previous 2 years.',
        created_at: ago(300),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
    ],
  },

  // ── Thread 3: pending — priyak asking productivity question ──
  {
    id: 'mock-thread-3',
    post_id: 'mock-4',
    creator_id: 'explore-guest',
    fan_id: 'mock-fan-priya',
    status: 'clarification',
    price: 20,
    answer_blocks: null,
    answer_text: null,
    answered_at: null,
    asker_has_viewed: true,
    purchase_count: 0,
    created_at: ago(60),
    updated_at: ago(60),
    post: {
      id: 'mock-4',
      image_urls: [],
      caption: 'Most productivity advice makes anxiety worse…',
    },
    creator: { ...ME },
    fan: {
      id: 'mock-fan-priya',
      username: 'priyak',
      display_name: 'Priya K',
      avatar_url: 'https://i.pravatar.cc/150?img=32',
    },
    messages: [
      {
        id: 'mock-msg-3a',
        thread_id: 'mock-thread-3',
        sender_id: 'mock-fan-priya',
        content: 'I\'ve tried every productivity system and always burn out after 2 weeks. What\'s the first thing you tell a client who comes to you completely exhausted from trying to "optimize"?',
        created_at: ago(60),
        sender: { id: 'mock-fan-priya', username: 'priyak', avatar_url: 'https://i.pravatar.cc/150?img=32' },
      },
      {
        id: 'mock-msg-3b',
        thread_id: 'mock-thread-3',
        sender_id: 'explore-guest',
        content: 'First thing is to stop. Seriously — no new systems for 2 weeks. Can you tell me what you were trying to optimize when it fell apart? Was it work, personal life, or both?',
        created_at: ago(50),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
      {
        id: 'mock-msg-3c',
        thread_id: 'mock-thread-3',
        sender_id: 'mock-fan-priya',
        content: 'Both honestly. I had a full Notion system, time-blocking, weekly reviews… it worked for like 10 days then completely collapsed.',
        created_at: ago(40),
        sender: { id: 'mock-fan-priya', username: 'priyak', avatar_url: 'https://i.pravatar.cc/150?img=32' },
      },
      {
        id: 'mock-msg-3d',
        thread_id: 'mock-thread-3',
        sender_id: 'explore-guest',
        content: 'That collapse is actually useful data. It means the system had no slack — any disruption and the whole thing fails. My answer will go deep on this.',
        created_at: ago(30),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
    ],
  },

  // ── Thread 4: pending — tylerb asking startup question ──
  {
    id: 'mock-thread-4',
    post_id: 'mock-5',
    creator_id: 'explore-guest',
    fan_id: 'mock-fan-tyler',
    status: 'clarification',
    price: 18,
    answer_blocks: null,
    answer_text: null,
    answered_at: null,
    asker_has_viewed: true,
    purchase_count: 0,
    created_at: ago(25),
    updated_at: ago(25),
    post: {
      id: 'mock-5',
      image_urls: ['https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80'],
      caption: 'We hit $10K MRR in 4 months with zero paid ads…',
    },
    creator: { ...ME },
    fan: {
      id: 'mock-fan-tyler',
      username: 'tylerb',
      display_name: 'Tyler B',
      avatar_url: 'https://i.pravatar.cc/150?img=56',
    },
    messages: [
      {
        id: 'mock-msg-4a',
        thread_id: 'mock-thread-4',
        sender_id: 'mock-fan-tyler',
        content: 'What channel is doing most of the work for you right now? Is it content, community, or something else entirely?',
        created_at: ago(25),
        sender: { id: 'mock-fan-tyler', username: 'tylerb', avatar_url: 'https://i.pravatar.cc/150?img=56' },
      },
      {
        id: 'mock-msg-4b',
        thread_id: 'mock-thread-4',
        sender_id: 'explore-guest',
        content: 'Content did the heavy lifting early on — but it was very specific content. Quick question: what\'s your ICP? B2B or consumer?',
        created_at: ago(18),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
      {
        id: 'mock-msg-4c',
        thread_id: 'mock-thread-4',
        sender_id: 'mock-fan-tyler',
        content: 'B2B — small teams, 5-20 people. SaaS tool for async standups.',
        created_at: ago(12),
        sender: { id: 'mock-fan-tyler', username: 'tylerb', avatar_url: 'https://i.pravatar.cc/150?img=56' },
      },
      {
        id: 'mock-msg-4d',
        thread_id: 'mock-thread-4',
        sender_id: 'explore-guest',
        content: 'Perfect, that narrows it a lot. My full answer will cover the exact channel mix that works for async B2B tools — it\'s counterintuitive.',
        created_at: ago(5),
        sender: { id: 'explore-guest', username: 'you', avatar_url: null },
      },
    ],
  },
]

// ─── Mock profile questions (AMA queue) ───────────────────────────────────────

export const MOCK_PROFILE_QUESTIONS: ProfileQuestion[] = [
  {
    id: 'mock-pq-1',
    creator_id: 'mock-creator-1',
    asker_id: 'mock-fan-a',
    question: 'What\'s the single best investment for someone just starting out with only $500?',
    status: 'open',
    upvote_count: 84,
    answer_post_id: null,
    created_at: ago(240),
    asker: { username: 'jessicaw', display_name: 'Jessica W', avatar_url: 'https://i.pravatar.cc/150?img=9' },
  },
  {
    id: 'mock-pq-2',
    creator_id: 'mock-creator-1',
    asker_id: 'mock-fan-b',
    question: 'How do you think about asset allocation in your 30s vs your 20s? Did your strategy change a lot?',
    status: 'open',
    upvote_count: 61,
    answer_post_id: null,
    created_at: ago(360),
    asker: { username: 'marcot', display_name: 'Marco T', avatar_url: 'https://i.pravatar.cc/150?img=18' },
  },
  {
    id: 'mock-pq-3',
    creator_id: 'mock-creator-1',
    asker_id: 'mock-fan-c',
    question: 'Do you have any crypto exposure or do you think it\'s too speculative for a long-term portfolio?',
    status: 'open',
    upvote_count: 47,
    answer_post_id: null,
    created_at: ago(500),
    asker: { username: 'priyak', display_name: 'Priya K', avatar_url: 'https://i.pravatar.cc/150?img=32' },
  },
  {
    id: 'mock-pq-4',
    creator_id: 'mock-creator-1',
    asker_id: 'mock-fan-d',
    question: 'What was your biggest financial mistake and what would you do differently?',
    status: 'open',
    upvote_count: 39,
    answer_post_id: null,
    created_at: ago(700),
    asker: { username: 'tylerb', display_name: 'Tyler B', avatar_url: 'https://i.pravatar.cc/150?img=56' },
  },
  {
    id: 'mock-pq-5',
    creator_id: 'mock-creator-1',
    asker_id: 'mock-fan-e',
    question: 'How do you handle investing during market downturns — do you pause contributions or double down?',
    status: 'open',
    upvote_count: 28,
    answer_post_id: null,
    created_at: ago(900),
    asker: { username: 'amyw', display_name: 'Amy W', avatar_url: 'https://i.pravatar.cc/150?img=44' },
  },
]

// ─── Mock feed items (explore mode — full FeedItem shape with threads) ─────────

const COLOR_MAP: Record<string, string> = {
  'mock-creator-1': '#111',
  'mock-creator-2': '#8b5cf6',
  'mock-creator-3': '#0ea5e9',
  'mock-creator-4': '#dc2626',
  'mock-creator-5': '#7c3aed',
  'mock-creator-6': '#555',
  'mock-creator-7': '#555',
  'mock-creator-8': '#0ea5e9',
}

function creator(id: string, username: string, displayName: string, avatar: string, responseRate: number | null) {
  return {
    username,
    display_name: displayName,
    avatar_url: avatar,
    color: COLOR_MAP[id] ?? '#111',
    initials: displayName.split(' ').map((w: string) => w[0]).join('').toUpperCase().slice(0, 2),
    verified: false,
    response_rate: responseRate,
  }
}

function fmtAgo(minutes: number): string {
  if (minutes < 60)   return `${minutes}m ago`
  if (minutes < 1440) return `${Math.floor(minutes / 60)}h ago`
  return `${Math.floor(minutes / 1440)}d ago`
}

export const MOCK_FEED_ITEMS: FeedItem[] = [
  // ── 1. Alex Watts — paid finance post with 3 questioners ──
  {
    id: 'mock-1',
    creator: creator('mock-creator-1', 'alexwatts', 'Alex Watts', 'https://i.pravatar.cc/150?img=11', 94),
    time_ago: fmtAgo(18),
    views: 2841,
    type: 'qa',
    text: 'The single most important thing I did in my 20s was automate my investments before I could spend the money. Not budgeting. Not tracking expenses. Automation. Here\'s the exact setup I use that grew my portfolio to $240K by 28.',
    images: [],
    price: 15,
    isLocked: true,
    likes: 0, comments: 34, saves: 0,
    _slot: 'discovery',
    question: 'How did you actually start? Did you use an app or set it up through your employer?',
    asker: {
      username: 'jessicaw',
      avatar_url: 'https://i.pravatar.cc/150?img=9',
      purchase_count: 47,
      purchasers: [
        { username: 'jessicaw', avatar_url: 'https://i.pravatar.cc/150?img=9' },
        { username: 'marcot',   avatar_url: 'https://i.pravatar.cc/150?img=18' },
        { username: 'priyak',   avatar_url: 'https://i.pravatar.cc/150?img=32' },
      ],
    },
    replies: [
      { username: 'jessicaw', avatar_url: 'https://i.pravatar.cc/150?img=9',  question: 'How did you start? Did you use a specific app?', price: 12, time_ago: fmtAgo(18), cart_count: 5 },
      { username: 'marcot',   avatar_url: 'https://i.pravatar.cc/150?img=18', question: 'Did your strategy change when you hit $100K?',    price: 20, time_ago: fmtAgo(45), cart_count: 12 },
      { username: 'tylerb',   avatar_url: 'https://i.pravatar.cc/150?img=56', question: 'What % of income do you recommend for someone just starting?', price: 8, time_ago: fmtAgo(90), cart_count: 3 },
    ],
  },

  // ── 2. Sienna — free fitness post (no thread, post style) ──
  {
    id: 'mock-2',
    creator: creator('mock-creator-2', 'siennafit', 'Sienna Marlow', 'https://i.pravatar.cc/150?img=5', 88),
    time_ago: fmtAgo(45),
    views: 5104,
    type: 'post',
    text: 'I trained 6 days a week for 3 years and barely changed. Then I read one study that flipped everything I thought I knew about progressive overload. Sharing the full breakdown + my revised program.',
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80'],
    isLocked: false,
    likes: 0, comments: 58, saves: 0,
    _slot: 'discovery',
  },

  // ── 3. Marc — paid photography post with 2 questioners ──
  {
    id: 'mock-3',
    creator: creator('mock-creator-3', 'marclens', 'Marc Delacroix', 'https://i.pravatar.cc/150?img=15', 97),
    time_ago: fmtAgo(90),
    views: 9230,
    type: 'qa',
    text: 'Shot this entire campaign on a $300 lens. Art directors never believe me. The secret isn\'t the gear — it\'s the one lighting trick I use in every shoot that makes cheap glass look expensive.',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    ],
    price: 8,
    location_address: 'Paris, France',
    isLocked: true,
    likes: 0, comments: 91, saves: 0,
    _slot: 'discovery',
    question: 'What exact lighting setup do you use on location shoots?',
    asker: {
      username: 'amyw',
      avatar_url: 'https://i.pravatar.cc/150?img=44',
      purchase_count: 91,
      purchasers: [
        { username: 'amyw',    avatar_url: 'https://i.pravatar.cc/150?img=44' },
        { username: 'priyak',  avatar_url: 'https://i.pravatar.cc/150?img=32' },
      ],
    },
    replies: [
      { username: 'amyw',   avatar_url: 'https://i.pravatar.cc/150?img=44', question: 'What exact lighting setup do you use on location?',       price: 5,  time_ago: fmtAgo(90),  cart_count: 8 },
      { username: 'priyak', avatar_url: 'https://i.pravatar.cc/150?img=32', question: 'Does this work with natural light only or need a reflector?', price: 14, time_ago: fmtAgo(130), cart_count: 23 },
    ],
  },

  // ── 4. Dr. Jordan — paid mental health post with 3 questioners ──
  {
    id: 'mock-4',
    creator: creator('mock-creator-4', 'drjordanmind', 'Dr. Jordan Ellis', 'https://i.pravatar.cc/150?img=33', 82),
    time_ago: fmtAgo(200),
    views: 14700,
    type: 'qa',
    text: 'Most productivity advice makes anxiety worse. I\'m a psychologist and I see this destroy high performers constantly. The framework I give my clients instead — and why it works with your nervous system, not against it.',
    images: [],
    price: 20,
    isLocked: true,
    likes: 0, comments: 120, saves: 0,
    _slot: 'discovery',
    question: 'What\'s the first thing you tell clients who are completely burnt out from optimizing?',
    asker: {
      username: 'riacodes',
      avatar_url: 'https://i.pravatar.cc/150?img=41',
      purchase_count: 120,
      purchasers: [
        { username: 'riacodes',  avatar_url: 'https://i.pravatar.cc/150?img=41' },
        { username: 'jessicaw',  avatar_url: 'https://i.pravatar.cc/150?img=9' },
        { username: 'tylerb',    avatar_url: 'https://i.pravatar.cc/150?img=56' },
      ],
    },
    replies: [
      { username: 'riacodes',  avatar_url: 'https://i.pravatar.cc/150?img=41', question: 'What\'s the first thing you tell burnt-out clients?',              price: 25, time_ago: fmtAgo(200), cart_count: 14 },
      { username: 'jessicaw',  avatar_url: 'https://i.pravatar.cc/150?img=9',  question: 'Is there a specific breathing or regulation technique you recommend?', price: 15, time_ago: fmtAgo(260), cart_count: 6 },
      { username: 'tylerb',    avatar_url: 'https://i.pravatar.cc/150?img=56', question: 'How do you differentiate burnout from depression in a session?',     price: 30, time_ago: fmtAgo(310), cart_count: 19 },
    ],
  },

  // ── 5. Naomi — free startup post ──
  {
    id: 'mock-5',
    creator: creator('mock-creator-5', 'naomibuilds', 'Naomi Park', 'https://i.pravatar.cc/150?img=47', 91),
    time_ago: fmtAgo(320),
    views: 7880,
    type: 'post',
    text: 'We hit $10K MRR in 4 months with zero paid ads. The channel everyone ignores right now is doing most of the work. Happy to share the full breakdown — messaging strategy, conversion rates, everything.',
    images: ['https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80'],
    location_address: 'San Francisco, CA',
    isLocked: false,
    likes: 0, comments: 77, saves: 0,
    _slot: 'discovery',
  },

  // ── 6. Kaito — paid cooking post with 2 questioners ──
  {
    id: 'mock-6',
    creator: creator('mock-creator-6', 'chefkaito', 'Kaito Mori', 'https://i.pravatar.cc/150?img=53', 99),
    time_ago: fmtAgo(480),
    views: 22400,
    type: 'qa',
    text: 'After 12 years as a Michelin-starred sous chef, the technique home cooks almost always miss isn\'t seasoning or heat — it\'s this one thing that separates restaurant food from everything else.',
    images: [
      'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    price: 12,
    location_address: 'Tokyo, Japan',
    isLocked: true,
    likes: 0, comments: 203, saves: 0,
    _slot: 'discovery',
    question: 'Is this technique something you can do at home without professional equipment?',
    asker: {
      username: 'marcot',
      avatar_url: 'https://i.pravatar.cc/150?img=18',
      purchase_count: 203,
      purchasers: [
        { username: 'marcot',   avatar_url: 'https://i.pravatar.cc/150?img=18' },
        { username: 'amyw',     avatar_url: 'https://i.pravatar.cc/150?img=44' },
      ],
    },
    replies: [
      { username: 'marcot', avatar_url: 'https://i.pravatar.cc/150?img=18', question: 'Can you do this at home without professional equipment?',  price: 7,  time_ago: fmtAgo(480), cart_count: 4 },
      { username: 'amyw',   avatar_url: 'https://i.pravatar.cc/150?img=44', question: 'Does this apply to pasta dishes or mainly proteins/sauces?', price: 18, time_ago: fmtAgo(540), cart_count: 11 },
    ],
  },

  // ── 7. Sienna — free nutrition post ──
  {
    id: 'mock-7',
    creator: creator('mock-creator-2', 'siennafit', 'Sienna Marlow', 'https://i.pravatar.cc/150?img=5', 88),
    time_ago: fmtAgo(720),
    views: 3920,
    type: 'post',
    text: 'The exact meal prep I do every Sunday that keeps me at 15% body fat year-round without tracking calories. 45 mins of prep, covers 80% of my meals. Full recipe list and macros included.',
    images: ['https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80'],
    isLocked: false,
    likes: 0, comments: 44, saves: 0,
    _slot: 'followed',
  },

  // ── 8. Taylor — paid design post with 2 questioners ──
  {
    id: 'mock-8',
    creator: creator('mock-creator-7', 'taylordesigns', 'Taylor Rhodes', 'https://i.pravatar.cc/150?img=25', 76),
    time_ago: fmtAgo(900),
    views: 8100,
    type: 'qa',
    text: 'I redesigned a fintech app\'s onboarding and conversion went from 31% to 67% in 3 weeks. The change was embarrassingly simple. Sharing the before/after and the principle behind it.',
    images: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80'],
    price: 18,
    location_address: 'New York, NY',
    isLocked: true,
    likes: 0, comments: 65, saves: 0,
    _slot: 'discovery',
    question: 'Was it a copy change, a visual change, or a flow change that made the difference?',
    asker: {
      username: 'priyak',
      avatar_url: 'https://i.pravatar.cc/150?img=32',
      purchase_count: 65,
      purchasers: [
        { username: 'priyak',   avatar_url: 'https://i.pravatar.cc/150?img=32' },
        { username: 'riacodes', avatar_url: 'https://i.pravatar.cc/150?img=41' },
      ],
    },
    replies: [
      { username: 'priyak',   avatar_url: 'https://i.pravatar.cc/150?img=32', question: 'Was it copy, visual, or flow change that moved the needle?',    price: 22, time_ago: fmtAgo(900),  cart_count: 7 },
      { username: 'riacodes', avatar_url: 'https://i.pravatar.cc/150?img=41', question: 'How do you measure conversion on a mobile onboarding funnel?', price: 10, time_ago: fmtAgo(960),  cart_count: 2 },
    ],
  },

  // ── 9. Alex — free tax post ──
  {
    id: 'mock-9',
    creator: creator('mock-creator-1', 'alexwatts', 'Alex Watts', 'https://i.pravatar.cc/150?img=11', 94),
    time_ago: fmtAgo(1200),
    views: 18300,
    type: 'post',
    text: 'The tax move most W-2 employees don\'t know about that saved me $8,400 last year. Totally legal, takes 20 minutes to set up, and almost no one in your company is doing it.',
    images: [],
    isLocked: false,
    likes: 0, comments: 189, saves: 0,
    _slot: 'followed',
  },

  // ── 10. Ria — paid career post with 3 questioners ──
  {
    id: 'mock-10',
    creator: creator('mock-creator-8', 'riacodes', 'Ria Sharma', 'https://i.pravatar.cc/150?img=41', 85),
    time_ago: fmtAgo(1500),
    views: 31200,
    type: 'qa',
    text: 'Got offers from Google, Stripe, and Figma in the same month. The thing that actually moved the needle in interviews wasn\'t LeetCode — it was how I answered this one type of question differently than everyone else.',
    images: [],
    price: 25,
    isLocked: true,
    likes: 0, comments: 312, saves: 0,
    _slot: 'discovery',
    question: 'What type of question is it and how did you answer it differently?',
    asker: {
      username: 'marcot',
      avatar_url: 'https://i.pravatar.cc/150?img=18',
      purchase_count: 312,
      purchasers: [
        { username: 'marcot',   avatar_url: 'https://i.pravatar.cc/150?img=18' },
        { username: 'jessicaw', avatar_url: 'https://i.pravatar.cc/150?img=9' },
        { username: 'tylerb',   avatar_url: 'https://i.pravatar.cc/150?img=56' },
      ],
    },
    replies: [
      { username: 'marcot',   avatar_url: 'https://i.pravatar.cc/150?img=18', question: 'What type of question is it and how did you answer differently?',    price: 35, time_ago: fmtAgo(1500), cart_count: 17 },
      { username: 'jessicaw', avatar_url: 'https://i.pravatar.cc/150?img=9',  question: 'Did you have a coach or mentor helping you prep?',                   price: 18, time_ago: fmtAgo(1560), cart_count: 9 },
      { username: 'tylerb',   avatar_url: 'https://i.pravatar.cc/150?img=56', question: 'How long did it take from first application to all three offers?',    price: 28, time_ago: fmtAgo(1620), cart_count: 25 },
    ],
  },
]
