import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Search, ChevronRight, ChevronDown, X } from 'lucide-react'

interface Article { title: string; body: string[] }
interface Section  { icon: string; title: string; articles: Article[] }

const SECTIONS: Section[] = [
  {
    icon: '🔐',
    title: 'Account settings & security',
    articles: [
      {
        title: 'How do I create an OODLE account?',
        body: [
          'Download the OODLE app and tap "Sign up". You can register using your email address or continue with Apple or Google.',
          'Once registered you will receive a verification email. Tap the link inside to activate your account before logging in.',
          'After activating, complete your profile by adding a display name, profile photo, and a short bio so peers can find and recognise you.',
          'You can start as a peer right away. To unlock creator features and earn from answered questions, head to Settings → Creator Mode and complete the onboarding steps.',
        ],
      },
      {
        title: 'Accessing my account',
        body: [
          'Open the app and tap "Log in". Enter your registered email and password, or use the same third-party sign-in method you chose when you signed up.',
          'If you are locked out after too many failed attempts, tap "Forgot password?" and follow the reset instructions sent to your email.',
          'You can stay logged in across devices. To remove a device, go to Settings → Active sessions and tap "Sign out" next to any session you do not recognise.',
          'If you believe someone else has accessed your account, change your password immediately and enable two-factor authentication.',
        ],
      },
      {
        title: 'ID verification: Data protection and usage',
        body: [
          'OODLE requires ID verification before you can receive payouts or unlock higher earning limits. This protects creators and peers from fraud.',
          'We accept a government-issued photo ID such as a passport, driving licence, or national identity card. The document must be current and not expired.',
          'Your ID images are encrypted in transit and at rest. They are reviewed by our identity partner and are not stored on OODLE servers once verification is complete.',
          'Verification typically takes 10–30 minutes. If your submission is rejected, you will be told why and can resubmit with a clearer image or a different document.',
          'Your verified identity is never shared with other users or third-party advertisers.',
        ],
      },
      {
        title: 'Password, security question, and two-factor authentication',
        body: [
          'To change your password go to Settings → Account → Change password. You will need to enter your current password to confirm the update.',
          'Two-factor authentication (2FA) adds an extra layer of security. Once enabled, every new login requires a one-time code sent to your phone or generated by an authenticator app.',
          'To enable 2FA go to Settings → Security → Two-factor authentication and follow the on-screen steps.',
          'If you lose access to your 2FA method, use one of the backup codes generated when you first set it up. Keep these codes saved somewhere safe.',
          'OODLE staff will never ask for your password. If you receive a message asking for it, report the account immediately.',
        ],
      },
      {
        title: 'Phone verification: Secure your OODLE account',
        body: [
          'Adding a verified phone number gives you an extra recovery option if you ever lose access to your email.',
          'Go to Settings → Account → Phone number, enter your mobile number, and tap "Send code". Enter the 6-digit code you receive within 5 minutes.',
          'Your phone number is used only for security purposes. It is never displayed to other users or used for marketing without your consent.',
          'If you change your phone number, update it in Settings before you lose access to your old number to avoid being locked out.',
        ],
      },
    ],
  },
  {
    icon: '💼',
    title: 'Selling on OODLE',
    articles: [
      {
        title: 'Creating & editing your creator profile',
        body: [
          'Your creator profile is the first thing peers see. Add a high-quality profile photo, a concise bio that explains who you are, and at least one piece of content to get started.',
          'Tap your avatar → Edit profile to update your display name, bio, links, and cover image at any time.',
          'Verified creators receive a badge on their profile which increases trust and helps them appear higher in search results.',
          'Link your social accounts (Instagram, X, TikTok) from Settings → Linked accounts so peers can follow you across platforms.',
          'Consistency in your posting niche helps the algorithm recommend your content to the right audience.',
        ],
      },
      {
        title: 'Creating a Listing (how answered questions appear)',
        body: [
          'On OODLE, your "listings" are your answered questions. When you post a photo or video and a peer asks a question, you can reply via DM with a paid answer.',
          'Switch to Answer Mode inside the DM thread, compose your answer (text, photo, or video), and set your price before sending.',
          'Once you send the answer it is locked. The peer who asked is notified and can purchase it. Other peers who see the question under your post can also purchase the same answer.',
          'Think of each answered question as evergreen content — the more people who purchase it, the more you earn from a single answer.',
          'Set a default answer price in Settings → Creator → Default answer price so every new question starts with your preferred rate pre-filled.',
        ],
      },
      {
        title: 'Managing your answered questions',
        body: [
          'Head to your Inbox to see all incoming questions. Unanswered questions sit in the queue. Once you answer and a peer purchases it, it becomes visible under your post on the timeline.',
          'You can decline a question if it violates community guidelines or if you simply do not want to answer it. Declined questions are removed from your queue.',
          'To edit the price on a pending (unanswered) question, open the DM thread and tap the price badge in the header.',
          'Answered questions that have been purchased can no longer be edited or deleted. If a question contains sensitive information, contact support before answering.',
        ],
      },
      {
        title: "Can't find your answered question under a post?",
        body: [
          'Answered questions only appear under a post once at least one peer has purchased the answer. If no one has bought it yet, it will not be visible on the timeline.',
          'Check that the question is linked to the correct post. Open the DM thread and confirm the post thumbnail shown at the top of the conversation is the right one.',
          'If a question was answered but the purchase was refunded, the answer returns to a locked state and is removed from the public timeline.',
          'Content moderation review can temporarily hide an answered question if it was flagged. You will be notified if this happens.',
        ],
      },
      {
        title: "Understanding OODLE's creator levels",
        body: [
          'OODLE has four creator levels: Newcomer, Rising, Established, and Top Creator. Your level is calculated monthly based on earnings, response rate, content quality, and peer engagement.',
          'Higher levels unlock benefits including lower platform fees, earlier access to new features, priority support, and increased visibility in search and the Explore feed.',
          'Your level is reviewed on the 1st of each month. A drop in activity or an increase in negative reports can lower your level.',
          'To see your current level and progress metrics, go to your profile → Creator stats.',
          'Top Creator status requires at least 90 days of active posting and a maintained 4.8 star rating across all answered questions.',
        ],
      },
    ],
  },
  {
    icon: '📦',
    title: 'Order management',
    articles: [
      {
        title: "Managing your orders: A creator's guide to the OODLE process",
        body: [
          'When a peer purchases an answered question, it appears in your Earnings page as a completed order with the token amount, the buyer, and a timestamp.',
          'You do not need to do anything after a sale — the answer is automatically delivered to the buyer and unlocked on the post timeline.',
          'If the same question is purchased by multiple peers, each purchase is recorded as a separate order. You earn the full price for every buyer.',
          'Purchases enter a short holding period (typically 24 hours) before the amount is added to your available balance, allowing time for the buyer to raise any concerns.',
        ],
      },
      {
        title: 'Reviews and ratings explained',
        body: [
          'After purchasing and viewing an answer, peers can leave a star rating (1–5) and an optional written review. These appear on your creator profile.',
          'Your overall rating is the rolling average of all reviews received in the past 90 days. Older reviews carry less weight over time.',
          'You can respond publicly to any review from your Earnings page. Keep responses professional — responses are visible to all visitors of your profile.',
          'Reviews that contain personal information, offensive language, or false claims can be reported to OODLE for removal review.',
          'A rating below 4.0 sustained over 30 days may result in reduced visibility. If you receive a negative review, reach out to the peer through the resolution centre first.',
        ],
      },
      {
        title: 'Using the Resolution Centre',
        body: [
          'The Resolution Centre is where disputes between creators and peers are handled. Access it via Settings → Support → Resolution Centre.',
          'A peer can open a dispute if they believe the answer they purchased did not match what was described, or if content was misleading.',
          'You will receive a notification when a dispute is opened. You have 48 hours to respond with your side of the story and any supporting evidence.',
          'If both parties cannot reach an agreement, OODLE support steps in to make a final decision. This process usually takes 3–5 business days.',
          'Repeated unresolved disputes can affect your creator level and, in serious cases, result in account restrictions.',
        ],
      },
    ],
  },
  {
    icon: '💸',
    title: 'Withdrawals & finances',
    articles: [
      {
        title: 'Your earnings page',
        body: [
          'Go to Profile → Earnings to see a full breakdown of your income: total earned, pending balance, available for withdrawal, and a transaction-by-transaction history.',
          'Pending balance is money from recent purchases that has not yet cleared the 24-hour holding period. Available balance is ready to withdraw.',
          'Use the date filter to view earnings by day, week, month, or custom range. Export a CSV file for your own records at any time.',
          'The earnings page also shows how many times each answered question has been purchased, helping you identify your most valuable content.',
        ],
      },
      {
        title: 'Withdrawing your earnings & managing payout methods',
        body: [
          'To add a payout method go to Settings → Finances → Payout methods. OODLE supports bank transfer, PayPal, and select digital wallets depending on your country.',
          'You must complete ID verification before your first withdrawal. The minimum withdrawal amount is $10.00.',
          'Payouts are processed within 1–5 business days. Bank transfers may take an additional 1–3 days to appear in your account depending on your bank.',
          'To request a withdrawal, go to Earnings → Withdraw, enter the amount, choose your payout method, and confirm.',
          'Keep your payout details up to date. Withdrawals sent to an old or invalid account cannot be recalled and may be lost.',
        ],
      },
      {
        title: 'Early Payout',
        body: [
          'Eligible creators can request an Early Payout on earnings that are still in the holding period, before they clear the standard 24-hour window.',
          'Early Payout is available to creators at the Established level or above with a positive account standing.',
          'A small processing fee (currently 1.5%) applies to early payouts to cover the accelerated release.',
          'To request an early payout, go to Earnings → Withdraw → Early Payout and select the amount.',
        ],
      },
      {
        title: 'Creator taxes',
        body: [
          'Earnings from OODLE may be subject to income tax depending on your country of residence. OODLE does not withhold tax on creator earnings.',
          'You are responsible for declaring your OODLE income to your local tax authority. Keep records of all your earnings using the CSV export in your Earnings page.',
          'US-based creators who earn over $600 in a calendar year will receive a 1099-K form by January 31st of the following year.',
          'For creators outside the US, OODLE may be required to collect tax residency information. You will be prompted to complete this in Settings → Finances → Tax information.',
          'We recommend consulting a tax professional if you are unsure of your obligations as an independent creator.',
        ],
      },
    ],
  },
  {
    icon: '$?',
    title: 'Features & programs',
    articles: [
      {
        title: 'Personal Assistant for creators',
        body: [
          'The OODLE Personal Assistant is an AI-powered tool that helps you manage your inbox, draft answer ideas, and identify your top-performing questions.',
          'Access it from your Inbox by tapping the assistant icon in the top-right corner. It can suggest reply starters, flag questions with high purchase potential, and summarise your weekly performance.',
          'The assistant learns from your content style over time. The more you use it, the more tailored its suggestions become.',
          'Personal Assistant is available to Established and Top Creator tiers. It can be toggled off at any time in Settings → Creator tools.',
        ],
      },
      {
        title: 'Creator Plus Standard and Premium: Advanced tools for business growth',
        body: [
          'Creator Plus is OODLE\'s optional paid subscription for creators who want advanced analytics, priority support, and additional promotional tools.',
          'Standard ($9.99/month) includes extended earnings history, advanced stats per question, and early access to new creator features.',
          'Premium ($24.99/month) adds everything in Standard plus a dedicated account manager, boosted profile visibility, and access to OODLE promotional campaigns.',
          'Both tiers include a 7-day free trial. Cancel any time from Settings → Creator Plus — no contract or lock-in.',
          'Creator Plus does not reduce platform fees. See our Fee Schedule page for current rates.',
        ],
      },
      {
        title: 'Promoting your content with OODLE Boosts',
        body: [
          'OODLE Boosts let you pay to increase the visibility of a specific post or answered question in the Explore feed and search results.',
          'Set a daily budget (minimum $1.00), choose a duration (1, 3, or 7 days), and target by interest category or location.',
          'Boosted posts are marked with a small "Promoted" label so peers know they are sponsored. This keeps trust with your audience.',
          'Track boost performance from your Earnings page → Promotions tab to see reach, click-through rate, and additional purchases generated.',
        ],
      },
      {
        title: 'Using your OODLE Portfolio',
        body: [
          'The Portfolio section on your profile lets you pin up to 12 posts that best represent your content and expertise.',
          'Pinned portfolio posts appear in a featured grid at the top of your profile above your regular feed.',
          'To add a post to your portfolio, open the post, tap the three-dot menu, and select "Add to portfolio".',
          'Portfolio posts are a great way to showcase your most-answered, highest-rated questions so new peers immediately see the value you offer.',
        ],
      },
      {
        title: 'Setting Availability',
        body: [
          'Creators can set themselves as Available or Away from Settings → Creator → Availability.',
          'When set to Away, your profile shows an availability badge and incoming questions are paused. You will not appear in the Explore feed during this period.',
          'You can schedule availability in advance — for example, set yourself as Away for a week-long holiday and it will reactivate automatically.',
          'Questions asked while you are Away are queued and delivered when you return. Peers are shown your next available date so expectations are managed.',
        ],
      },
    ],
  },
  {
    icon: '🛡️',
    title: 'Trust & Safety',
    articles: [
      {
        title: 'Our Community Standards',
        body: [
          'OODLE is built on respect, authenticity, and creative freedom. All users — creators and peers — are expected to treat each other with dignity.',
          'Prohibited behaviour includes harassment, hate speech, impersonation, distributing explicit content without proper age gates, and any form of financial fraud.',
          'Content that depicts violence, exploitation, or illegal activity will be removed immediately and may result in a permanent ban without refund.',
          'Our standards apply to posts, DMs, answers, reviews, and profile information. No part of OODLE is exempt.',
          'Community Standards are reviewed regularly. Significant updates will be communicated via in-app notification and email.',
        ],
      },
      {
        title: 'Avoiding spam and staying safe on OODLE',
        body: [
          'Spam includes sending unsolicited bulk messages, artificially inflating purchase counts, posting repetitive or misleading content to game search rankings.',
          'Do not click links sent by other users in DMs unless you fully trust the sender. OODLE links will always come from an oodle.app domain.',
          'If another user is pressuring you to move communication off-platform, this is a red flag. OODLE cannot protect you from fraud that happens outside the app.',
          'Never share your login credentials, payout details, or ID documents with anyone claiming to be from OODLE. Our team will never ask for these.',
          'Use the block feature freely if a user makes you uncomfortable. Blocked users cannot see your content or send you messages.',
        ],
      },
      {
        title: 'How to report content or behaviour on OODLE',
        body: [
          'To report a post, tap the three-dot menu on the post and select "Report". Choose the reason that best applies and add any additional context.',
          'To report a user, go to their profile, tap the three-dot menu in the header, and select "Report account".',
          'To report a DM or question, press and hold the message to reveal the report option.',
          'Reports are reviewed by our Trust & Safety team within 24 hours for high-severity cases and 72 hours for standard cases.',
          'You will receive a notification when action is taken on your report. We take all reports seriously, even if the outcome is not always visible to you.',
        ],
      },
      {
        title: "Stay protected: OODLE's off-platform policy",
        body: [
          'All transactions on OODLE must go through the in-app token system. Attempting to arrange payment outside the app (cash, bank transfer, external platforms) violates our Terms of Service.',
          'Off-platform transactions remove all buyer and seller protections, including refunds, dispute resolution, and fraud prevention.',
          'If a user asks you to pay or collect money outside of OODLE, report it immediately. This is the most common form of fraud on creator platforms.',
          'OODLE\'s off-platform policy exists to protect both parties. Creators who consistently attempt to redirect transactions off-platform will have their accounts suspended.',
        ],
      },
      {
        title: 'ID verification: Data protection and usage',
        body: [
          'Identity verification is required for all creators who want to receive payouts. It is optional for peers unless they wish to spend above a certain token threshold.',
          'We partner with an FCA-regulated identity verification provider. Your document images are processed securely and are not visible to OODLE employees.',
          'OODLE is fully compliant with GDPR and CCPA. You have the right to request deletion of your personal data at any time from Settings → Privacy → Data requests.',
          'Verified identity information is used solely to comply with financial regulations (KYC/AML). It is never sold or shared with advertisers.',
          'If you believe your personal data has been mishandled, contact our Data Protection Officer at privacy@oodle.app.',
        ],
      },
    ],
  },
]

const POPULAR = [
  { title: 'How do I create an OODLE account?',               section: 0, article: 0 },
  { title: 'Withdrawing your earnings & managing payout methods', section: 3, article: 1 },
  { title: 'Creating a Listing (how answered questions appear)', section: 1, article: 1 },
  { title: "Understanding OODLE's creator levels",              section: 1, article: 4 },
]

interface ArticleDetail { sectionIdx: number; articleIdx: number }

export default function HelpCenterPage() {
  const navigate = useNavigate()
  const [query, setQuery]             = useState('')
  const [openSection, setOpenSection] = useState<number | null>(null)
  const [detail, setDetail]           = useState<ArticleDetail | null>(null)

  // Filtered view for search
  const filtered = query.trim()
    ? SECTIONS.map((s, si) => ({
        ...s,
        _si: si,
        articles: s.articles
          .map((a, ai) => ({ ...a, _ai: ai }))
          .filter(a => a.title.toLowerCase().includes(query.toLowerCase())),
      })).filter(s => s.articles.length > 0)
    : null

  // ── Article detail overlay ──────────────────────────────────────────────
  if (detail) {
    const article = SECTIONS[detail.sectionIdx].articles[detail.articleIdx]
    const section = SECTIONS[detail.sectionIdx]
    return (
      <div className="min-h-screen bg-white pb-20">
        <div className="sticky top-0 z-30 bg-white border-b border-gray-100 flex items-center gap-3 px-4 pt-5 pb-3">
          <button onClick={() => setDetail(null)} className="p-1.5 hover:bg-gray-50 rounded-full">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex-1 min-w-0">
            <p className="text-[11px] text-gray-400 truncate">{section.icon} {section.title}</p>
            <p className="text-[14px] font-semibold text-gray-900 leading-tight">{article.title}</p>
          </div>
        </div>

        <div className="px-5 pt-5 pb-10">
          <div className="flex flex-col gap-5">
            {article.body.map((para, i) => (
              <p key={i} className="text-[14px] text-gray-700 leading-relaxed">{para}</p>
            ))}
          </div>

          {/* Was this helpful */}
          <div className="mt-10 bg-gray-50 rounded-2xl px-5 py-5 text-center">
            <p className="font-semibold text-[14px] text-gray-900 mb-3">Was this helpful?</p>
            <div className="flex justify-center gap-3">
              <button className="px-5 py-2 rounded-xl border border-gray-200 text-[13px] text-gray-600 hover:bg-white">
                👍 Yes
              </button>
              <button className="px-5 py-2 rounded-xl border border-gray-200 text-[13px] text-gray-600 hover:bg-white">
                👎 No
              </button>
            </div>
          </div>

          {/* Related articles in same section */}
          {SECTIONS[detail.sectionIdx].articles.filter((_, i) => i !== detail.articleIdx).length > 0 && (
            <div className="mt-8">
              <p className="text-[13px] font-semibold text-gray-900 mb-3">Related articles</p>
              <div className="flex flex-col gap-1">
                {SECTIONS[detail.sectionIdx].articles
                  .map((a, ai) => ai !== detail.articleIdx ? { a, ai } : null)
                  .filter((x): x is { a: Article; ai: number } => x !== null)
                  .map(({ a, ai }) => (
                    <button key={ai}
                      onClick={() => setDetail({ sectionIdx: detail.sectionIdx, articleIdx: ai })}
                      className="flex items-center justify-between py-3 px-4 bg-gray-50 rounded-2xl text-left">
                      <span className="text-[13px] text-gray-700 flex-1 pr-2">{a.title}</span>
                      <ChevronRight className="w-4 h-4 text-gray-400 flex-shrink-0" />
                    </button>
                  ))}
              </div>
            </div>
          )}
        </div>
      </div>
    )
  }

  // ── Main help center ────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-white pb-20">

      {/* Header */}
      <div className="sticky top-0 z-30 bg-white border-b border-gray-100">
        <div className="flex items-center gap-3 px-4 pt-5 pb-3">
          <button onClick={() => navigate(-1)} className="p-1.5 hover:bg-gray-50 rounded-full">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex-1">
            <p className="text-[11px] font-bold text-black uppercase tracking-widest">OODLE</p>
            <h1 className="text-[17px] font-bold text-gray-900 leading-tight">Help Center</h1>
          </div>
        </div>

        {/* Search */}
        <div className="px-4 pb-4">
          <div className="flex items-center gap-2.5 bg-gray-100 rounded-2xl px-4 py-2.5">
            <Search className="w-4 h-4 text-gray-400 flex-shrink-0" />
            <input
              value={query}
              onChange={e => { setQuery(e.target.value); setOpenSection(null) }}
              placeholder="Search help articles…"
              className="flex-1 bg-transparent text-[14px] text-gray-900 placeholder-gray-400 focus:outline-none"
            />
            {query ? (
              <button onClick={() => setQuery('')}>
                <X className="w-4 h-4 text-gray-400" />
              </button>
            ) : null}
          </div>
        </div>
      </div>

      {/* ── SEARCH RESULTS ── */}
      {query && filtered !== null && (
        <div className="px-4 pt-4">
          {filtered.length === 0 ? (
            <div className="text-center py-16">
              <p className="text-4xl mb-3">🔍</p>
              <p className="font-semibold text-gray-800 mb-1">No results for "{query}"</p>
              <p className="text-[13px] text-gray-400">Try different keywords or browse by topic below</p>
            </div>
          ) : (
            <>
              <p className="text-[12px] text-gray-400 mb-3">
                {filtered.reduce((n, s) => n + s.articles.length, 0)} results
              </p>
              <div className="flex flex-col gap-1">
                {filtered.map(section =>
                  section.articles.map(article => (
                    <button
                      key={article.title}
                      onClick={() => { setQuery(''); setDetail({ sectionIdx: section._si, articleIdx: article._ai }) }}
                      className="flex items-start gap-3 py-3.5 px-4 bg-gray-50 rounded-2xl text-left"
                    >
                      <span className="text-lg flex-shrink-0 mt-0.5">{section.icon}</span>
                      <div className="flex-1 min-w-0">
                        <p className="text-[13px] text-gray-900 font-medium leading-snug">{article.title}</p>
                        <p className="text-[11px] text-gray-400 mt-0.5">{section.title}</p>
                      </div>
                      <ChevronRight className="w-4 h-4 text-gray-300 flex-shrink-0 mt-0.5" />
                    </button>
                  ))
                )}
              </div>
            </>
          )}
        </div>
      )}

      {/* ── DEFAULT VIEW ── */}
      {!query && (
        <>
          {/* Hero */}
          <div className="mx-4 mt-4 mb-5 bg-black rounded-3xl px-5 py-6 text-white">
            <p className="text-[12px] font-semibold uppercase tracking-wider opacity-80 mb-1">Welcome to</p>
            <p className="text-[22px] font-bold mb-1">OODLE Help Center</p>
            <p className="text-[13px] opacity-80 leading-relaxed">
              Find answers, guides, and support for everything on OODLE.
            </p>
          </div>

          {/* Popular articles */}
          <div className="px-4 mb-6">
            <p className="text-[13px] font-semibold text-gray-900 mb-3">Popular Articles</p>
            <div className="flex flex-col gap-1">
              {POPULAR.map(p => (
                <button
                  key={p.title}
                  onClick={() => setDetail({ sectionIdx: p.section, articleIdx: p.article })}
                  className="flex items-center justify-between py-3 px-4 bg-gray-50 rounded-2xl text-left"
                >
                  <span className="text-[13px] text-gray-700 flex-1 pr-2">{p.title}</span>
                  <ChevronRight className="w-4 h-4 text-gray-400 flex-shrink-0" />
                </button>
              ))}
            </div>
          </div>

          {/* Sections accordion */}
          <div className="px-4">
            <p className="text-[13px] font-semibold text-gray-900 mb-3">Browse by topic</p>
            <div className="flex flex-col gap-3">
              {SECTIONS.map((section, si) => {
                const isOpen = openSection === si
                return (
                  <div key={section.title} className="border border-gray-100 rounded-2xl overflow-hidden">
                    <button
                      onClick={() => setOpenSection(prev => prev === si ? null : si)}
                      className="w-full flex items-center gap-3 px-4 py-4 text-left hover:bg-gray-50 transition-colors"
                    >
                      <span className="text-xl flex-shrink-0">{section.icon}</span>
                      <span className="flex-1 font-medium text-[14px] text-gray-900">{section.title}</span>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <span className="text-[11px] text-gray-400">{section.articles.length}</span>
                        <ChevronDown
                          className={`w-4 h-4 text-gray-400 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
                        />
                      </div>
                    </button>

                    {isOpen && (
                      <div className="border-t border-gray-100">
                        {section.articles.map((article, ai) => (
                          <button
                            key={article.title}
                            onClick={() => setDetail({ sectionIdx: si, articleIdx: ai })}
                            className={`w-full flex items-center justify-between px-4 py-3.5 text-left hover:bg-gray-50 transition-colors ${
                              ai < section.articles.length - 1 ? 'border-b border-gray-50' : ''
                            }`}
                          >
                            <span className="text-[13px] text-gray-600 flex-1 pr-3 leading-snug">
                              {article.title}
                            </span>
                            <ChevronRight className="w-4 h-4 text-gray-300 flex-shrink-0" />
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </div>

          {/* Footer CTA */}
          <div className="mx-4 mt-8 bg-gray-50 rounded-3xl px-5 py-5 text-center">
            <p className="text-[14px] font-semibold text-gray-900 mb-1">Still need help?</p>
            <p className="text-[12px] text-gray-400 mb-4">Our support team typically replies within 2 hours</p>
            <button className="bg-gray-900 text-white text-[13px] font-medium px-6 py-3 rounded-xl">
              Contact Support
            </button>
          </div>
        </>
      )}
    </div>
  )
}
